---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: pathim
spec:
  ports:
    - name: redis-cli
      port: 6379
      targetPort: 6379
      nodePort: 6379
  selector:
    app: redis
  type: NodePort
---