---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-msgcallback-rpc
  namespace: pathim
data:
  msgcallback.yaml: |-
    Name: msgcallback-rpc
    ListenOn: :8080
    Log:
      ServiceName: msgcallback-rpc
      Level: info
    Prometheus:
      Host: 0.0.0.0
      Port: 80
      Path: /metrics
    Telemetry:
      Name: msgcallback-rpc
      Endpoint: http://101.43.214.203:14268/api/traces
      Sampler: 1.0
      Batcher: jaeger
